'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { QueryClient, QueryClientProvider, useQuery } from 'react-query'

const queryClient = new QueryClient()

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
      <body
        style={{
          backgroundImage:
            "linear-gradient(45deg, rgba(183, 204, 248, 0.717), rgba(7, 43, 127, 0.679)), url('/background.jpg')",
        }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased  min-h-screen bg-cover bg-center bg-no-repeat`}
      >
        {children}
      </body>
    </QueryClientProvider>
      
    </html>
  );
}
